### PR TITLE
Update just-wait and use npm bins

### PR DESCRIPTION
**Pull request by ghost**
This should work the exact same, but much cleaner.

https://docs.npmjs.com/files/folders#executables

### CODE REVIEW

**Comment by RickWong** [comment]
Hi, thanks. But the reason those paths are relative, is to avoid having to install npm binaries globally.

**Comment by ghost** [comment]
Hey @RickWong,

When you NPM install a project with code like I have, the dependencies which have a bin object in their package.json will auto-install their binaries via symlink.

Are you worries my changes will cause you to need to -g install those packages? If so, give it a shot, you don't need to.

**Comment by ghost** [comment]
> When in local mode, executables are linked into ./node_modules/.bin so that they can be made available to scripts run through npm. (For example, so that a test runner will be in the path when you run npm test.).

**Comment by RickWong** [comment]
Thanks @lostthetrail

**Pull request merged**
